# Generated by Django 2.1.3 on 2019-02-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to='static/')),
            ],
        ),
    ]
